name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet build src -c Release
      - uses: actions/upload-artifact@v4
        with:
          name: ModBlocker
          path: src/bin/Release/net472/ModBlocker.dll
